### ISSUE TITLE
Additional WebP files without changing original files

### ISSUE THREAD

**Issue by pumano** [bcheidemann/squoosh-webpack-plugin#1]
Hello! Love to see the adoption of squoosh as webpack plugin!

It's possible to create webp files for my jpg / png files with same name without changing original files? 
I want to create separate webp files with same name and `.webp` and then serve it via nginx content negotiation, by checking `"accept"` header for `image/webp` with fallback to original png / jpeg files

**Comment by bcheidemann** [comment]
> Hello! Love to see the adoption of squoosh as webpack plugin!
> 
> It's possible to create webp files for my jpg / png files with same name without changing original files? I want to create separate webp files with same name and `.webp` and then serve it via nginx content negotiation, by checking `"accept"` header for `image/webp` with fallback to original png / jpeg files

Hey, that's a great use case I hadn't thought of! I am currently working on making the plugin more adaptable and flexible - this ties in nicely with that goal :D I will release an update by the end of the week which will enable this functionality. Thanks for the raising the issue!

**Comment by pumano** [comment]
@bcheidemann Wow! Thank you!! I will waiting for that!

**Comment by FuryJohnson** [comment]
@bcheidemann Hey! I Have the same issue, waiting your update!

**Comment by bcheidemann** [comment]
Haha I better do it tonight then! :D Thank you both for taking the time to leave feedback - it's nice to see people are taking an interest in the plugin :)

**Comment by pumano** [comment]
@bcheidemann [imagemin](https://github.com/imagemin) maintainer does not maintain more their projects and they need specific libraries aka libpng-dev and etc for working and he recommends squoosh (because its maintained by google team and also utilize webassembly without native binaries). Only your project support squoosh as webpack plugin.

**Comment by bcheidemann** [comment]
@pumano @FuryJohnson Just a quick update on the status of this issue. I'm working on restructuring some of the code to make development easier but this took longer than expected so I wasn't able to finish it last night. I will hopefully have time to complete this tonight and I will address this issue immediately after.

**Comment by FuryJohnson** [comment]
@bcheidemann Thanks! I'm still waiting and will update version in my project :) After then, I can tell you about my results in project

**Comment by bcheidemann** [comment]
Hey @pumano @FuryJohnson, thanks for your patience :)

I have published version `2.0.0-alpha.1` to NPM and updated the documentation at [squoosh-webpack-plugin.info](https://squoosh-webpack-plugin.info/).

To facilitate your use case, I have added an option called `preserveFileName` which when set to `true` will only change the extension. Additionally, the `outDir` option no longer has a default value and if not defined, the plugin will output the encoded images to the same folder as the original image.

I will leave this as alpha for a week or two in case there are any issues so please let me know how you get on.

**Comment by bcheidemann** [comment]
I am closing the issue for now but if there are issues with `2.0.0-alpha.1` I will reopen it until they are fixed.

**Comment by pumano** [comment]
@bcheidemann would love to test it tomorrow morning. Thank you for that awesome contribution!
